import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Ms_Madi , Montserrat_Alternates,Montserrat } from "next/font/google";

const madi = Ms_Madi({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-madi",
});

const montAlt = Montserrat_Alternates ({
  subsets: ["latin"],
  weight: ["100", "200", "400"],
  variable: "--font-mont-alt",
})

const mont = Montserrat ({
  subsets: ["latin"],
  weight: ["100"],
  variable: "--font-mont",
})


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${madi.variable} ${montAlt.variable}`} >
      <body>{children}</body>
    </html>
  );
}
